/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Auth');
goog.provide('proto.Auth.PersonaRef');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.PersonaId');
goog.require('proto.UserId');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Auth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Auth.repeatedFields_, null);
};
goog.inherits(proto.Auth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Auth.displayName = 'proto.Auth';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Auth.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Auth.prototype.toObject = function(opt_includeInstance) {
  return proto.Auth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Auth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Auth.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: (f = msg.getUserId()) && proto.UserId.toObject(includeInstance, f),
    personasList: jspb.Message.toObjectList(msg.getPersonasList(),
    proto.Auth.PersonaRef.toObject, includeInstance),
    createdDatetimeMs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    modifiedDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    loginDatetimeMs: jspb.Message.getFieldWithDefault(msg, 6, 0),
    loginIpAddress: msg.getLoginIpAddress_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Auth}
 */
proto.Auth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Auth;
  return proto.Auth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Auth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Auth}
 */
proto.Auth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UserId;
      reader.readMessage(value,proto.UserId.deserializeBinaryFromReader);
      msg.setUserId(value);
      break;
    case 2:
      var value = new proto.Auth.PersonaRef;
      reader.readMessage(value,proto.Auth.PersonaRef.deserializeBinaryFromReader);
      msg.addPersonas(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedDatetimeMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModifiedDatetimeMs(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLoginDatetimeMs(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setLoginIpAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Auth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Auth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Auth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Auth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.UserId.serializeBinaryToWriter
    );
  }
  f = message.getPersonasList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Auth.PersonaRef.serializeBinaryToWriter
    );
  }
  f = message.getCreatedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getModifiedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getLoginDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getLoginIpAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Auth.PersonaRef = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Auth.PersonaRef, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Auth.PersonaRef.displayName = 'proto.Auth.PersonaRef';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Auth.PersonaRef.prototype.toObject = function(opt_includeInstance) {
  return proto.Auth.PersonaRef.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Auth.PersonaRef} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Auth.PersonaRef.toObject = function(includeInstance, msg) {
  var f, obj = {
    extName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    personaId: (f = msg.getPersonaId()) && proto.PersonaId.toObject(includeInstance, f),
    createdDatetimeMs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    modifiedDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    loginDatetimeMs: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Auth.PersonaRef}
 */
proto.Auth.PersonaRef.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Auth.PersonaRef;
  return proto.Auth.PersonaRef.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Auth.PersonaRef} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Auth.PersonaRef}
 */
proto.Auth.PersonaRef.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtName(value);
      break;
    case 2:
      var value = new proto.PersonaId;
      reader.readMessage(value,proto.PersonaId.deserializeBinaryFromReader);
      msg.setPersonaId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedDatetimeMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModifiedDatetimeMs(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLoginDatetimeMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Auth.PersonaRef.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Auth.PersonaRef.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Auth.PersonaRef} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Auth.PersonaRef.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExtName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPersonaId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PersonaId.serializeBinaryToWriter
    );
  }
  f = message.getCreatedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getModifiedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getLoginDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string ext_name = 1;
 * @return {string}
 */
proto.Auth.PersonaRef.prototype.getExtName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.Auth.PersonaRef.prototype.setExtName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional PersonaId persona_id = 2;
 * @return {?proto.PersonaId}
 */
proto.Auth.PersonaRef.prototype.getPersonaId = function() {
  return /** @type{?proto.PersonaId} */ (
    jspb.Message.getWrapperField(this, proto.PersonaId, 2));
};


/** @param {?proto.PersonaId|undefined} value */
proto.Auth.PersonaRef.prototype.setPersonaId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.Auth.PersonaRef.prototype.clearPersonaId = function() {
  this.setPersonaId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Auth.PersonaRef.prototype.hasPersonaId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 created_datetime_ms = 3;
 * @return {number}
 */
proto.Auth.PersonaRef.prototype.getCreatedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.Auth.PersonaRef.prototype.setCreatedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 modified_datetime_ms = 4;
 * @return {number}
 */
proto.Auth.PersonaRef.prototype.getModifiedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Auth.PersonaRef.prototype.setModifiedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 login_datetime_ms = 5;
 * @return {number}
 */
proto.Auth.PersonaRef.prototype.getLoginDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.Auth.PersonaRef.prototype.setLoginDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional UserId user_id = 1;
 * @return {?proto.UserId}
 */
proto.Auth.prototype.getUserId = function() {
  return /** @type{?proto.UserId} */ (
    jspb.Message.getWrapperField(this, proto.UserId, 1));
};


/** @param {?proto.UserId|undefined} value */
proto.Auth.prototype.setUserId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Auth.prototype.clearUserId = function() {
  this.setUserId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Auth.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated PersonaRef personas = 2;
 * @return {!Array<!proto.Auth.PersonaRef>}
 */
proto.Auth.prototype.getPersonasList = function() {
  return /** @type{!Array<!proto.Auth.PersonaRef>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Auth.PersonaRef, 2));
};


/** @param {!Array<!proto.Auth.PersonaRef>} value */
proto.Auth.prototype.setPersonasList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Auth.PersonaRef=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Auth.PersonaRef}
 */
proto.Auth.prototype.addPersonas = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Auth.PersonaRef, opt_index);
};


proto.Auth.prototype.clearPersonasList = function() {
  this.setPersonasList([]);
};


/**
 * optional int64 created_datetime_ms = 3;
 * @return {number}
 */
proto.Auth.prototype.getCreatedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.Auth.prototype.setCreatedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 modified_datetime_ms = 4;
 * @return {number}
 */
proto.Auth.prototype.getModifiedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Auth.prototype.setModifiedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 login_datetime_ms = 6;
 * @return {number}
 */
proto.Auth.prototype.getLoginDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.Auth.prototype.setLoginDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bytes login_ip_address = 7;
 * @return {string}
 */
proto.Auth.prototype.getLoginIpAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes login_ip_address = 7;
 * This is a type-conversion wrapper around `getLoginIpAddress()`
 * @return {string}
 */
proto.Auth.prototype.getLoginIpAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getLoginIpAddress()));
};


/**
 * optional bytes login_ip_address = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getLoginIpAddress()`
 * @return {!Uint8Array}
 */
proto.Auth.prototype.getLoginIpAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getLoginIpAddress()));
};


/** @param {!(string|Uint8Array)} value */
proto.Auth.prototype.setLoginIpAddress = function(value) {
  jspb.Message.setProto3BytesField(this, 7, value);
};


