/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.MessageId');
goog.require('proto.OrgId');
goog.require('proto.PersonaId');

goog.forwardDeclare('proto.MessageStatus');
goog.forwardDeclare('proto.MessageType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Message.displayName = 'proto.Message';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageId: (f = msg.getMessageId()) && proto.MessageId.toObject(includeInstance, f),
    messageType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createdDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    modifiedDatetimeMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
    createPersonaId: (f = msg.getCreatePersonaId()) && proto.PersonaId.toObject(includeInstance, f),
    createOrgId: (f = msg.getCreateOrgId()) && proto.OrgId.toObject(includeInstance, f),
    messageBody: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Message;
  return proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MessageId;
      reader.readMessage(value,proto.MessageId.deserializeBinaryFromReader);
      msg.setMessageId(value);
      break;
    case 2:
      var value = /** @type {!proto.MessageType} */ (reader.readEnum());
      msg.setMessageType(value);
      break;
    case 3:
      var value = /** @type {!proto.MessageStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedDatetimeMs(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModifiedDatetimeMs(value);
      break;
    case 6:
      var value = new proto.PersonaId;
      reader.readMessage(value,proto.PersonaId.deserializeBinaryFromReader);
      msg.setCreatePersonaId(value);
      break;
    case 7:
      var value = new proto.OrgId;
      reader.readMessage(value,proto.OrgId.deserializeBinaryFromReader);
      msg.setCreateOrgId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.MessageId.serializeBinaryToWriter
    );
  }
  f = message.getMessageType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreatedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getModifiedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCreatePersonaId();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.PersonaId.serializeBinaryToWriter
    );
  }
  f = message.getCreateOrgId();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.OrgId.serializeBinaryToWriter
    );
  }
  f = message.getMessageBody();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional MessageId message_id = 1;
 * @return {?proto.MessageId}
 */
proto.Message.prototype.getMessageId = function() {
  return /** @type{?proto.MessageId} */ (
    jspb.Message.getWrapperField(this, proto.MessageId, 1));
};


/** @param {?proto.MessageId|undefined} value */
proto.Message.prototype.setMessageId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Message.prototype.clearMessageId = function() {
  this.setMessageId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasMessageId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional MessageType message_type = 2;
 * @return {!proto.MessageType}
 */
proto.Message.prototype.getMessageType = function() {
  return /** @type {!proto.MessageType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.MessageType} value */
proto.Message.prototype.setMessageType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional MessageStatus status = 3;
 * @return {!proto.MessageStatus}
 */
proto.Message.prototype.getStatus = function() {
  return /** @type {!proto.MessageStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.MessageStatus} value */
proto.Message.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int64 created_datetime_ms = 4;
 * @return {number}
 */
proto.Message.prototype.getCreatedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Message.prototype.setCreatedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 modified_datetime_ms = 5;
 * @return {number}
 */
proto.Message.prototype.getModifiedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.Message.prototype.setModifiedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional PersonaId create_persona_id = 6;
 * @return {?proto.PersonaId}
 */
proto.Message.prototype.getCreatePersonaId = function() {
  return /** @type{?proto.PersonaId} */ (
    jspb.Message.getWrapperField(this, proto.PersonaId, 6));
};


/** @param {?proto.PersonaId|undefined} value */
proto.Message.prototype.setCreatePersonaId = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.Message.prototype.clearCreatePersonaId = function() {
  this.setCreatePersonaId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasCreatePersonaId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional OrgId create_org_id = 7;
 * @return {?proto.OrgId}
 */
proto.Message.prototype.getCreateOrgId = function() {
  return /** @type{?proto.OrgId} */ (
    jspb.Message.getWrapperField(this, proto.OrgId, 7));
};


/** @param {?proto.OrgId|undefined} value */
proto.Message.prototype.setCreateOrgId = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.Message.prototype.clearCreateOrgId = function() {
  this.setCreateOrgId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasCreateOrgId = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string message_body = 8;
 * @return {string}
 */
proto.Message.prototype.getMessageBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.Message.prototype.setMessageBody = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


