/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.MessageRef');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.MessageId');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MessageRef = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MessageRef, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MessageRef.displayName = 'proto.MessageRef';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MessageRef.prototype.toObject = function(opt_includeInstance) {
  return proto.MessageRef.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MessageRef} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageRef.toObject = function(includeInstance, msg) {
  var f, obj = {
    refMessageId: (f = msg.getRefMessageId()) && proto.MessageId.toObject(includeInstance, f),
    originalMessageId: (f = msg.getOriginalMessageId()) && proto.MessageId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MessageRef}
 */
proto.MessageRef.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MessageRef;
  return proto.MessageRef.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MessageRef} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MessageRef}
 */
proto.MessageRef.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MessageId;
      reader.readMessage(value,proto.MessageId.deserializeBinaryFromReader);
      msg.setRefMessageId(value);
      break;
    case 2:
      var value = new proto.MessageId;
      reader.readMessage(value,proto.MessageId.deserializeBinaryFromReader);
      msg.setOriginalMessageId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MessageRef.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MessageRef.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MessageRef} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageRef.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefMessageId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.MessageId.serializeBinaryToWriter
    );
  }
  f = message.getOriginalMessageId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MessageId.serializeBinaryToWriter
    );
  }
};


/**
 * optional MessageId ref_message_id = 1;
 * @return {?proto.MessageId}
 */
proto.MessageRef.prototype.getRefMessageId = function() {
  return /** @type{?proto.MessageId} */ (
    jspb.Message.getWrapperField(this, proto.MessageId, 1));
};


/** @param {?proto.MessageId|undefined} value */
proto.MessageRef.prototype.setRefMessageId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.MessageRef.prototype.clearRefMessageId = function() {
  this.setRefMessageId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MessageRef.prototype.hasRefMessageId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional MessageId original_message_id = 2;
 * @return {?proto.MessageId}
 */
proto.MessageRef.prototype.getOriginalMessageId = function() {
  return /** @type{?proto.MessageId} */ (
    jspb.Message.getWrapperField(this, proto.MessageId, 2));
};


/** @param {?proto.MessageId|undefined} value */
proto.MessageRef.prototype.setOriginalMessageId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.MessageRef.prototype.clearOriginalMessageId = function() {
  this.setOriginalMessageId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MessageRef.prototype.hasOriginalMessageId = function() {
  return jspb.Message.getField(this, 2) != null;
};


