/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Org');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.OrgId');

goog.forwardDeclare('proto.OrgStatus');
goog.forwardDeclare('proto.OrgType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Org = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Org, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Org.displayName = 'proto.Org';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Org.prototype.toObject = function(opt_includeInstance) {
  return proto.Org.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Org} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Org.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: (f = msg.getOrgId()) && proto.OrgId.toObject(includeInstance, f),
    orgType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createdDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    modifiedDatetimeMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
    displayName: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Org}
 */
proto.Org.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Org;
  return proto.Org.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Org} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Org}
 */
proto.Org.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.OrgId;
      reader.readMessage(value,proto.OrgId.deserializeBinaryFromReader);
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {!proto.OrgType} */ (reader.readEnum());
      msg.setOrgType(value);
      break;
    case 3:
      var value = /** @type {!proto.OrgStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedDatetimeMs(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModifiedDatetimeMs(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Org.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Org.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Org} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Org.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.OrgId.serializeBinaryToWriter
    );
  }
  f = message.getOrgType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreatedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getModifiedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional OrgId org_id = 1;
 * @return {?proto.OrgId}
 */
proto.Org.prototype.getOrgId = function() {
  return /** @type{?proto.OrgId} */ (
    jspb.Message.getWrapperField(this, proto.OrgId, 1));
};


/** @param {?proto.OrgId|undefined} value */
proto.Org.prototype.setOrgId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Org.prototype.clearOrgId = function() {
  this.setOrgId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Org.prototype.hasOrgId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OrgType org_type = 2;
 * @return {!proto.OrgType}
 */
proto.Org.prototype.getOrgType = function() {
  return /** @type {!proto.OrgType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.OrgType} value */
proto.Org.prototype.setOrgType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional OrgStatus status = 3;
 * @return {!proto.OrgStatus}
 */
proto.Org.prototype.getStatus = function() {
  return /** @type {!proto.OrgStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.OrgStatus} value */
proto.Org.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int64 created_datetime_ms = 4;
 * @return {number}
 */
proto.Org.prototype.getCreatedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Org.prototype.setCreatedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 modified_datetime_ms = 5;
 * @return {number}
 */
proto.Org.prototype.getModifiedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.Org.prototype.setModifiedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string display_name = 6;
 * @return {string}
 */
proto.Org.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.Org.prototype.setDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


