/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Session');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.PersonaId');
goog.require('proto.SessionId');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Session = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Session, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Session.displayName = 'proto.Session';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Session.prototype.toObject = function(opt_includeInstance) {
  return proto.Session.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Session} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Session.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionId: (f = msg.getSessionId()) && proto.SessionId.toObject(includeInstance, f),
    personaId: (f = msg.getPersonaId()) && proto.PersonaId.toObject(includeInstance, f),
    startDatetimeMs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    expireDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Session}
 */
proto.Session.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Session;
  return proto.Session.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Session} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Session}
 */
proto.Session.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SessionId;
      reader.readMessage(value,proto.SessionId.deserializeBinaryFromReader);
      msg.setSessionId(value);
      break;
    case 2:
      var value = new proto.PersonaId;
      reader.readMessage(value,proto.PersonaId.deserializeBinaryFromReader);
      msg.setPersonaId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartDatetimeMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpireDatetimeMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Session.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Session.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Session} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Session.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SessionId.serializeBinaryToWriter
    );
  }
  f = message.getPersonaId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PersonaId.serializeBinaryToWriter
    );
  }
  f = message.getStartDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getExpireDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional SessionId session_id = 1;
 * @return {?proto.SessionId}
 */
proto.Session.prototype.getSessionId = function() {
  return /** @type{?proto.SessionId} */ (
    jspb.Message.getWrapperField(this, proto.SessionId, 1));
};


/** @param {?proto.SessionId|undefined} value */
proto.Session.prototype.setSessionId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Session.prototype.clearSessionId = function() {
  this.setSessionId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Session.prototype.hasSessionId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PersonaId persona_id = 2;
 * @return {?proto.PersonaId}
 */
proto.Session.prototype.getPersonaId = function() {
  return /** @type{?proto.PersonaId} */ (
    jspb.Message.getWrapperField(this, proto.PersonaId, 2));
};


/** @param {?proto.PersonaId|undefined} value */
proto.Session.prototype.setPersonaId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.Session.prototype.clearPersonaId = function() {
  this.setPersonaId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Session.prototype.hasPersonaId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 start_datetime_ms = 3;
 * @return {number}
 */
proto.Session.prototype.getStartDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.Session.prototype.setStartDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 expire_datetime_ms = 4;
 * @return {number}
 */
proto.Session.prototype.getExpireDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Session.prototype.setExpireDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


