/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.User');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.PersonaId');
goog.require('proto.UserId');

goog.forwardDeclare('proto.UserStatus');
goog.forwardDeclare('proto.UserType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.User.displayName = 'proto.User';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.User.prototype.toObject = function(opt_includeInstance) {
  return proto.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: (f = msg.getUserId()) && proto.UserId.toObject(includeInstance, f),
    userType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createdDatetimeMs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    modifiedDatetimeMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
    givenName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    familyName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 8, ""),
    defaultPersonaId: (f = msg.getDefaultPersonaId()) && proto.PersonaId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.User}
 */
proto.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.User;
  return proto.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.User}
 */
proto.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UserId;
      reader.readMessage(value,proto.UserId.deserializeBinaryFromReader);
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {!proto.UserType} */ (reader.readEnum());
      msg.setUserType(value);
      break;
    case 3:
      var value = /** @type {!proto.UserStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedDatetimeMs(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModifiedDatetimeMs(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setGivenName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamilyName(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 9:
      var value = new proto.PersonaId;
      reader.readMessage(value,proto.PersonaId.deserializeBinaryFromReader);
      msg.setDefaultPersonaId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.UserId.serializeBinaryToWriter
    );
  }
  f = message.getUserType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreatedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getModifiedDatetimeMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getGivenName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getFamilyName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDefaultPersonaId();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.PersonaId.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserId user_id = 1;
 * @return {?proto.UserId}
 */
proto.User.prototype.getUserId = function() {
  return /** @type{?proto.UserId} */ (
    jspb.Message.getWrapperField(this, proto.UserId, 1));
};


/** @param {?proto.UserId|undefined} value */
proto.User.prototype.setUserId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.User.prototype.clearUserId = function() {
  this.setUserId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.User.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional UserType user_type = 2;
 * @return {!proto.UserType}
 */
proto.User.prototype.getUserType = function() {
  return /** @type {!proto.UserType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.UserType} value */
proto.User.prototype.setUserType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional UserStatus status = 3;
 * @return {!proto.UserStatus}
 */
proto.User.prototype.getStatus = function() {
  return /** @type {!proto.UserStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.UserStatus} value */
proto.User.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int64 created_datetime_ms = 4;
 * @return {number}
 */
proto.User.prototype.getCreatedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.User.prototype.setCreatedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 modified_datetime_ms = 5;
 * @return {number}
 */
proto.User.prototype.getModifiedDatetimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.User.prototype.setModifiedDatetimeMs = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string given_name = 6;
 * @return {string}
 */
proto.User.prototype.getGivenName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.User.prototype.setGivenName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string family_name = 7;
 * @return {string}
 */
proto.User.prototype.getFamilyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.User.prototype.setFamilyName = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string display_name = 8;
 * @return {string}
 */
proto.User.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.User.prototype.setDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional PersonaId default_persona_id = 9;
 * @return {?proto.PersonaId}
 */
proto.User.prototype.getDefaultPersonaId = function() {
  return /** @type{?proto.PersonaId} */ (
    jspb.Message.getWrapperField(this, proto.PersonaId, 9));
};


/** @param {?proto.PersonaId|undefined} value */
proto.User.prototype.setDefaultPersonaId = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.User.prototype.clearDefaultPersonaId = function() {
  this.setDefaultPersonaId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.User.prototype.hasDefaultPersonaId = function() {
  return jspb.Message.getField(this, 9) != null;
};


