// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sliki-model.proto

package sliki_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type UserType int32

const (
	UserType_USER_PERSONAL  UserType = 0
	UserType_USER_ORG_BASED UserType = 1
)

var UserType_name = map[int32]string{
	0: "USER_PERSONAL",
	1: "USER_ORG_BASED",
}

var UserType_value = map[string]int32{
	"USER_PERSONAL":  0,
	"USER_ORG_BASED": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{0}
}

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type UserStatus int32

const (
	UserStatus_USER_ACTIVE     UserStatus = 0
	UserStatus_USER_UNVERIFIED UserStatus = 1
	UserStatus_USER_SUSPENDED  UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "USER_ACTIVE",
	1: "USER_UNVERIFIED",
	2: "USER_SUSPENDED",
}

var UserStatus_value = map[string]int32{
	"USER_ACTIVE":     0,
	"USER_UNVERIFIED": 1,
	"USER_SUSPENDED":  2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{1}
}

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type PersonaType int32

const (
	PersonaType_PERSONA_REGULAR PersonaType = 0
)

var PersonaType_name = map[int32]string{
	0: "PERSONA_REGULAR",
}

var PersonaType_value = map[string]int32{
	"PERSONA_REGULAR": 0,
}

func (x PersonaType) String() string {
	return proto.EnumName(PersonaType_name, int32(x))
}

func (PersonaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{2}
}

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type PersonaStatus int32

const (
	PersonaStatus_PERSONA_ACTIVE PersonaStatus = 0
)

var PersonaStatus_name = map[int32]string{
	0: "PERSONA_ACTIVE",
}

var PersonaStatus_value = map[string]int32{
	"PERSONA_ACTIVE": 0,
}

func (x PersonaStatus) String() string {
	return proto.EnumName(PersonaStatus_name, int32(x))
}

func (PersonaStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{3}
}

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type OrgType int32

const (
	OrgType_ORG_NON_PROFIT_OTHER       OrgType = 0
	OrgType_ORG_NON_PROFIT_EDUCATIONAL OrgType = 1
	OrgType_ORG_NON_PROFIT_RELIGIOUS   OrgType = 2
	OrgType_ORG_NON_PROFIT_GOVERNMENT  OrgType = 3
	OrgType_ORG_FOR_PROFIT_OTHER       OrgType = 4
	OrgType_ORG_FOR_PROFIT_SMALL       OrgType = 5
	OrgType_ORG_FOR_PROFIT_LARGE       OrgType = 6
)

var OrgType_name = map[int32]string{
	0: "ORG_NON_PROFIT_OTHER",
	1: "ORG_NON_PROFIT_EDUCATIONAL",
	2: "ORG_NON_PROFIT_RELIGIOUS",
	3: "ORG_NON_PROFIT_GOVERNMENT",
	4: "ORG_FOR_PROFIT_OTHER",
	5: "ORG_FOR_PROFIT_SMALL",
	6: "ORG_FOR_PROFIT_LARGE",
}

var OrgType_value = map[string]int32{
	"ORG_NON_PROFIT_OTHER":       0,
	"ORG_NON_PROFIT_EDUCATIONAL": 1,
	"ORG_NON_PROFIT_RELIGIOUS":   2,
	"ORG_NON_PROFIT_GOVERNMENT":  3,
	"ORG_FOR_PROFIT_OTHER":       4,
	"ORG_FOR_PROFIT_SMALL":       5,
	"ORG_FOR_PROFIT_LARGE":       6,
}

func (x OrgType) String() string {
	return proto.EnumName(OrgType_name, int32(x))
}

func (OrgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{4}
}

// note that PB's enum scoping rules require values to be globally unique,
// hence seemingly redundant prefixes.
type OrgStatus int32

const (
	OrgStatus_ORG_ACTIVE OrgStatus = 0
)

var OrgStatus_name = map[int32]string{
	0: "ORG_ACTIVE",
}

var OrgStatus_value = map[string]int32{
	"ORG_ACTIVE": 0,
}

func (x OrgStatus) String() string {
	return proto.EnumName(OrgStatus_name, int32(x))
}

func (OrgStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{5}
}

type GroupType int32

const (
	GroupType_GROUP_PERSONAL GroupType = 0
	GroupType_GROUP_ORG      GroupType = 1
)

var GroupType_name = map[int32]string{
	0: "GROUP_PERSONAL",
	1: "GROUP_ORG",
}

var GroupType_value = map[string]int32{
	"GROUP_PERSONAL": 0,
	"GROUP_ORG":      1,
}

func (x GroupType) String() string {
	return proto.EnumName(GroupType_name, int32(x))
}

func (GroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{6}
}

type GroupVisibility int32

const (
	GroupVisibility_GROUP_PUBLIC  GroupVisibility = 0
	GroupVisibility_GROUP_PRIVATE GroupVisibility = 1
)

var GroupVisibility_name = map[int32]string{
	0: "GROUP_PUBLIC",
	1: "GROUP_PRIVATE",
}

var GroupVisibility_value = map[string]int32{
	"GROUP_PUBLIC":  0,
	"GROUP_PRIVATE": 1,
}

func (x GroupVisibility) String() string {
	return proto.EnumName(GroupVisibility_name, int32(x))
}

func (GroupVisibility) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{7}
}

type GroupStatus int32

const (
	GroupStatus_GROUP_ACTIVE GroupStatus = 0
)

var GroupStatus_name = map[int32]string{
	0: "GROUP_ACTIVE",
}

var GroupStatus_value = map[string]int32{
	"GROUP_ACTIVE": 0,
}

func (x GroupStatus) String() string {
	return proto.EnumName(GroupStatus_name, int32(x))
}

func (GroupStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{8}
}

type MessageType int32

const (
	MessageType_MSG_SIMPLE MessageType = 0
	MessageType_MSG_THREAD MessageType = 1
)

var MessageType_name = map[int32]string{
	0: "MSG_SIMPLE",
	1: "MSG_THREAD",
}

var MessageType_value = map[string]int32{
	"MSG_SIMPLE": 0,
	"MSG_THREAD": 1,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{9}
}

type MessageStatus int32

const (
	MessageStatus_MSG_VISIBLE MessageStatus = 0
)

var MessageStatus_name = map[int32]string{
	0: "MSG_VISIBLE",
}

var MessageStatus_value = map[string]int32{
	"MSG_VISIBLE": 0,
}

func (x MessageStatus) String() string {
	return proto.EnumName(MessageStatus_name, int32(x))
}

func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{10}
}

type UserId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type User struct {
	UserId               *UserId    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType             UserType   `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=UserType" json:"user_type,omitempty"`
	Status               UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=UserStatus" json:"status,omitempty"`
	CreatedDatetimeMs    int64      `protobuf:"varint,4,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs   int64      `protobuf:"varint,5,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	GivenName            string     `protobuf:"bytes,6,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string     `protobuf:"bytes,7,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	DisplayName          string     `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string     `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	DefaultPersonaId     *PersonaId `protobuf:"bytes,10,opt,name=default_persona_id,json=defaultPersonaId,proto3" json:"default_persona_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() *UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *User) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_USER_PERSONAL
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_USER_ACTIVE
}

func (m *User) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *User) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *User) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *User) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetDefaultPersonaId() *PersonaId {
	if m != nil {
		return m.DefaultPersonaId
	}
	return nil
}

type PersonaId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonaId) Reset()         { *m = PersonaId{} }
func (m *PersonaId) String() string { return proto.CompactTextString(m) }
func (*PersonaId) ProtoMessage()    {}
func (*PersonaId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{2}
}

func (m *PersonaId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonaId.Unmarshal(m, b)
}
func (m *PersonaId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonaId.Marshal(b, m, deterministic)
}
func (m *PersonaId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonaId.Merge(m, src)
}
func (m *PersonaId) XXX_Size() int {
	return xxx_messageInfo_PersonaId.Size(m)
}
func (m *PersonaId) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonaId.DiscardUnknown(m)
}

var xxx_messageInfo_PersonaId proto.InternalMessageInfo

func (m *PersonaId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Persona struct {
	PersonaId            *PersonaId    `protobuf:"bytes,1,opt,name=persona_id,json=personaId,proto3" json:"persona_id,omitempty"`
	PersonaType          PersonaType   `protobuf:"varint,2,opt,name=persona_type,json=personaType,proto3,enum=PersonaType" json:"persona_type,omitempty"`
	Status               PersonaStatus `protobuf:"varint,3,opt,name=status,proto3,enum=PersonaStatus" json:"status,omitempty"`
	UserId               *UserId       `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedDatetimeMs    int64         `protobuf:"varint,5,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs   int64         `protobuf:"varint,6,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	DisplayName          string        `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string        `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Persona) Reset()         { *m = Persona{} }
func (m *Persona) String() string { return proto.CompactTextString(m) }
func (*Persona) ProtoMessage()    {}
func (*Persona) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{3}
}

func (m *Persona) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persona.Unmarshal(m, b)
}
func (m *Persona) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persona.Marshal(b, m, deterministic)
}
func (m *Persona) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persona.Merge(m, src)
}
func (m *Persona) XXX_Size() int {
	return xxx_messageInfo_Persona.Size(m)
}
func (m *Persona) XXX_DiscardUnknown() {
	xxx_messageInfo_Persona.DiscardUnknown(m)
}

var xxx_messageInfo_Persona proto.InternalMessageInfo

func (m *Persona) GetPersonaId() *PersonaId {
	if m != nil {
		return m.PersonaId
	}
	return nil
}

func (m *Persona) GetPersonaType() PersonaType {
	if m != nil {
		return m.PersonaType
	}
	return PersonaType_PERSONA_REGULAR
}

func (m *Persona) GetStatus() PersonaStatus {
	if m != nil {
		return m.Status
	}
	return PersonaStatus_PERSONA_ACTIVE
}

func (m *Persona) GetUserId() *UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Persona) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Persona) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Persona) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Persona) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OrgId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgId) Reset()         { *m = OrgId{} }
func (m *OrgId) String() string { return proto.CompactTextString(m) }
func (*OrgId) ProtoMessage()    {}
func (*OrgId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{4}
}

func (m *OrgId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgId.Unmarshal(m, b)
}
func (m *OrgId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgId.Marshal(b, m, deterministic)
}
func (m *OrgId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgId.Merge(m, src)
}
func (m *OrgId) XXX_Size() int {
	return xxx_messageInfo_OrgId.Size(m)
}
func (m *OrgId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgId.DiscardUnknown(m)
}

var xxx_messageInfo_OrgId proto.InternalMessageInfo

func (m *OrgId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Org struct {
	OrgId                *OrgId    `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgType              OrgType   `protobuf:"varint,2,opt,name=org_type,json=orgType,proto3,enum=OrgType" json:"org_type,omitempty"`
	Status               OrgStatus `protobuf:"varint,3,opt,name=status,proto3,enum=OrgStatus" json:"status,omitempty"`
	CreatedDatetimeMs    int64     `protobuf:"varint,4,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs   int64     `protobuf:"varint,5,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	DisplayName          string    `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string    `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Org) Reset()         { *m = Org{} }
func (m *Org) String() string { return proto.CompactTextString(m) }
func (*Org) ProtoMessage()    {}
func (*Org) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{5}
}

func (m *Org) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Org.Unmarshal(m, b)
}
func (m *Org) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Org.Marshal(b, m, deterministic)
}
func (m *Org) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Org.Merge(m, src)
}
func (m *Org) XXX_Size() int {
	return xxx_messageInfo_Org.Size(m)
}
func (m *Org) XXX_DiscardUnknown() {
	xxx_messageInfo_Org.DiscardUnknown(m)
}

var xxx_messageInfo_Org proto.InternalMessageInfo

func (m *Org) GetOrgId() *OrgId {
	if m != nil {
		return m.OrgId
	}
	return nil
}

func (m *Org) GetOrgType() OrgType {
	if m != nil {
		return m.OrgType
	}
	return OrgType_ORG_NON_PROFIT_OTHER
}

func (m *Org) GetStatus() OrgStatus {
	if m != nil {
		return m.Status
	}
	return OrgStatus_ORG_ACTIVE
}

func (m *Org) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Org) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Org) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Org) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GroupId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupId) Reset()         { *m = GroupId{} }
func (m *GroupId) String() string { return proto.CompactTextString(m) }
func (*GroupId) ProtoMessage()    {}
func (*GroupId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{6}
}

func (m *GroupId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupId.Unmarshal(m, b)
}
func (m *GroupId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupId.Marshal(b, m, deterministic)
}
func (m *GroupId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupId.Merge(m, src)
}
func (m *GroupId) XXX_Size() int {
	return xxx_messageInfo_GroupId.Size(m)
}
func (m *GroupId) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupId.DiscardUnknown(m)
}

var xxx_messageInfo_GroupId proto.InternalMessageInfo

func (m *GroupId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Group struct {
	GroupId              *GroupId        `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupType            GroupType       `protobuf:"varint,2,opt,name=group_type,json=groupType,proto3,enum=GroupType" json:"group_type,omitempty"`
	Visibility           GroupVisibility `protobuf:"varint,3,opt,name=visibility,proto3,enum=GroupVisibility" json:"visibility,omitempty"`
	Status               GroupStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=GroupStatus" json:"status,omitempty"`
	CreatedDatetimeMs    int64           `protobuf:"varint,5,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs   int64           `protobuf:"varint,6,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	DisplayName          string          `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string          `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{7}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() *GroupId {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *Group) GetGroupType() GroupType {
	if m != nil {
		return m.GroupType
	}
	return GroupType_GROUP_PERSONAL
}

func (m *Group) GetVisibility() GroupVisibility {
	if m != nil {
		return m.Visibility
	}
	return GroupVisibility_GROUP_PUBLIC
}

func (m *Group) GetStatus() GroupStatus {
	if m != nil {
		return m.Status
	}
	return GroupStatus_GROUP_ACTIVE
}

func (m *Group) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Group) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Group) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MessageId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageId) Reset()         { *m = MessageId{} }
func (m *MessageId) String() string { return proto.CompactTextString(m) }
func (*MessageId) ProtoMessage()    {}
func (*MessageId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{8}
}

func (m *MessageId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageId.Unmarshal(m, b)
}
func (m *MessageId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageId.Marshal(b, m, deterministic)
}
func (m *MessageId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageId.Merge(m, src)
}
func (m *MessageId) XXX_Size() int {
	return xxx_messageInfo_MessageId.Size(m)
}
func (m *MessageId) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageId.DiscardUnknown(m)
}

var xxx_messageInfo_MessageId proto.InternalMessageInfo

func (m *MessageId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Message struct {
	MessageId            *MessageId    `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType          MessageType   `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=MessageType" json:"message_type,omitempty"`
	Status               MessageStatus `protobuf:"varint,3,opt,name=status,proto3,enum=MessageStatus" json:"status,omitempty"`
	CreatedDatetimeMs    int64         `protobuf:"varint,4,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs   int64         `protobuf:"varint,5,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	CreatedPersonaId     *PersonaId    `protobuf:"bytes,6,opt,name=created_persona_id,json=createdPersonaId,proto3" json:"created_persona_id,omitempty"`
	CreateOrgId          *OrgId        `protobuf:"bytes,7,opt,name=create_org_id,json=createOrgId,proto3" json:"create_org_id,omitempty"`
	MessageBody          string        `protobuf:"bytes,8,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{9}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageId() *MessageId {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *Message) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_MSG_SIMPLE
}

func (m *Message) GetStatus() MessageStatus {
	if m != nil {
		return m.Status
	}
	return MessageStatus_MSG_VISIBLE
}

func (m *Message) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Message) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Message) GetCreatedPersonaId() *PersonaId {
	if m != nil {
		return m.CreatedPersonaId
	}
	return nil
}

func (m *Message) GetCreateOrgId() *OrgId {
	if m != nil {
		return m.CreateOrgId
	}
	return nil
}

func (m *Message) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

type MessageRef struct {
	RefMessageId         *MessageId `protobuf:"bytes,1,opt,name=ref_message_id,json=refMessageId,proto3" json:"ref_message_id,omitempty"`
	OriginalMessageId    *MessageId `protobuf:"bytes,2,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageRef) Reset()         { *m = MessageRef{} }
func (m *MessageRef) String() string { return proto.CompactTextString(m) }
func (*MessageRef) ProtoMessage()    {}
func (*MessageRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{10}
}

func (m *MessageRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRef.Unmarshal(m, b)
}
func (m *MessageRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRef.Marshal(b, m, deterministic)
}
func (m *MessageRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRef.Merge(m, src)
}
func (m *MessageRef) XXX_Size() int {
	return xxx_messageInfo_MessageRef.Size(m)
}
func (m *MessageRef) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRef.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRef proto.InternalMessageInfo

func (m *MessageRef) GetRefMessageId() *MessageId {
	if m != nil {
		return m.RefMessageId
	}
	return nil
}

func (m *MessageRef) GetOriginalMessageId() *MessageId {
	if m != nil {
		return m.OriginalMessageId
	}
	return nil
}

type DocId struct {
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocId) Reset()         { *m = DocId{} }
func (m *DocId) String() string { return proto.CompactTextString(m) }
func (*DocId) ProtoMessage()    {}
func (*DocId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{11}
}

func (m *DocId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocId.Unmarshal(m, b)
}
func (m *DocId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocId.Marshal(b, m, deterministic)
}
func (m *DocId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocId.Merge(m, src)
}
func (m *DocId) XXX_Size() int {
	return xxx_messageInfo_DocId.Size(m)
}
func (m *DocId) XXX_DiscardUnknown() {
	xxx_messageInfo_DocId.DiscardUnknown(m)
}

var xxx_messageInfo_DocId proto.InternalMessageInfo

func (m *DocId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Doc struct {
	DocId                *DocId   `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Doc) Reset()         { *m = Doc{} }
func (m *Doc) String() string { return proto.CompactTextString(m) }
func (*Doc) ProtoMessage()    {}
func (*Doc) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{12}
}

func (m *Doc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doc.Unmarshal(m, b)
}
func (m *Doc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doc.Marshal(b, m, deterministic)
}
func (m *Doc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doc.Merge(m, src)
}
func (m *Doc) XXX_Size() int {
	return xxx_messageInfo_Doc.Size(m)
}
func (m *Doc) XXX_DiscardUnknown() {
	xxx_messageInfo_Doc.DiscardUnknown(m)
}

var xxx_messageInfo_Doc proto.InternalMessageInfo

func (m *Doc) GetDocId() *DocId {
	if m != nil {
		return m.DocId
	}
	return nil
}

type Auth struct {
	UserId             *UserId            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Personas           []*Auth_PersonaRef `protobuf:"bytes,2,rep,name=personas,proto3" json:"personas,omitempty"`
	CreatedDatetimeMs  int64              `protobuf:"varint,3,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs int64              `protobuf:"varint,4,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	// note that login does not count as a modification
	LoginDatetimeMs      int64    `protobuf:"varint,6,opt,name=login_datetime_ms,json=loginDatetimeMs,proto3" json:"login_datetime_ms,omitempty"`
	LoginIpAddress       []byte   `protobuf:"bytes,7,opt,name=login_ip_address,json=loginIpAddress,proto3" json:"login_ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{13}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetUserId() *UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Auth) GetPersonas() []*Auth_PersonaRef {
	if m != nil {
		return m.Personas
	}
	return nil
}

func (m *Auth) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Auth) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Auth) GetLoginDatetimeMs() int64 {
	if m != nil {
		return m.LoginDatetimeMs
	}
	return 0
}

func (m *Auth) GetLoginIpAddress() []byte {
	if m != nil {
		return m.LoginIpAddress
	}
	return nil
}

type Auth_PersonaRef struct {
	ExtName            string     `protobuf:"bytes,1,opt,name=ext_name,json=extName,proto3" json:"ext_name,omitempty"`
	PersonaId          *PersonaId `protobuf:"bytes,2,opt,name=persona_id,json=personaId,proto3" json:"persona_id,omitempty"`
	CreatedDatetimeMs  int64      `protobuf:"varint,3,opt,name=created_datetime_ms,json=createdDatetimeMs,proto3" json:"created_datetime_ms,omitempty"`
	ModifiedDatetimeMs int64      `protobuf:"varint,4,opt,name=modified_datetime_ms,json=modifiedDatetimeMs,proto3" json:"modified_datetime_ms,omitempty"`
	// note that login does not count as a modification
	LoginDatetimeMs      int64    `protobuf:"varint,5,opt,name=login_datetime_ms,json=loginDatetimeMs,proto3" json:"login_datetime_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_PersonaRef) Reset()         { *m = Auth_PersonaRef{} }
func (m *Auth_PersonaRef) String() string { return proto.CompactTextString(m) }
func (*Auth_PersonaRef) ProtoMessage()    {}
func (*Auth_PersonaRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{13, 0}
}

func (m *Auth_PersonaRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_PersonaRef.Unmarshal(m, b)
}
func (m *Auth_PersonaRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_PersonaRef.Marshal(b, m, deterministic)
}
func (m *Auth_PersonaRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_PersonaRef.Merge(m, src)
}
func (m *Auth_PersonaRef) XXX_Size() int {
	return xxx_messageInfo_Auth_PersonaRef.Size(m)
}
func (m *Auth_PersonaRef) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_PersonaRef.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_PersonaRef proto.InternalMessageInfo

func (m *Auth_PersonaRef) GetExtName() string {
	if m != nil {
		return m.ExtName
	}
	return ""
}

func (m *Auth_PersonaRef) GetPersonaId() *PersonaId {
	if m != nil {
		return m.PersonaId
	}
	return nil
}

func (m *Auth_PersonaRef) GetCreatedDatetimeMs() int64 {
	if m != nil {
		return m.CreatedDatetimeMs
	}
	return 0
}

func (m *Auth_PersonaRef) GetModifiedDatetimeMs() int64 {
	if m != nil {
		return m.ModifiedDatetimeMs
	}
	return 0
}

func (m *Auth_PersonaRef) GetLoginDatetimeMs() int64 {
	if m != nil {
		return m.LoginDatetimeMs
	}
	return 0
}

type AuthRec struct {
	ExtId                string   `protobuf:"bytes,1,opt,name=ext_id,json=extId,proto3" json:"ext_id,omitempty"`
	PwHash               []byte   `protobuf:"bytes,2,opt,name=pw_hash,json=pwHash,proto3" json:"pw_hash,omitempty"`
	PwSalt               []byte   `protobuf:"bytes,3,opt,name=pw_salt,json=pwSalt,proto3" json:"pw_salt,omitempty"`
	Auth                 *Auth    `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRec) Reset()         { *m = AuthRec{} }
func (m *AuthRec) String() string { return proto.CompactTextString(m) }
func (*AuthRec) ProtoMessage()    {}
func (*AuthRec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{14}
}

func (m *AuthRec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRec.Unmarshal(m, b)
}
func (m *AuthRec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRec.Marshal(b, m, deterministic)
}
func (m *AuthRec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRec.Merge(m, src)
}
func (m *AuthRec) XXX_Size() int {
	return xxx_messageInfo_AuthRec.Size(m)
}
func (m *AuthRec) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRec.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRec proto.InternalMessageInfo

func (m *AuthRec) GetExtId() string {
	if m != nil {
		return m.ExtId
	}
	return ""
}

func (m *AuthRec) GetPwHash() []byte {
	if m != nil {
		return m.PwHash
	}
	return nil
}

func (m *AuthRec) GetPwSalt() []byte {
	if m != nil {
		return m.PwSalt
	}
	return nil
}

func (m *AuthRec) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type SessionId struct {
	// 32-byte session_id
	BinaryUuid           []byte   `protobuf:"bytes,1,opt,name=binary_uuid,json=binaryUuid,proto3" json:"binary_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionId) Reset()         { *m = SessionId{} }
func (m *SessionId) String() string { return proto.CompactTextString(m) }
func (*SessionId) ProtoMessage()    {}
func (*SessionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{15}
}

func (m *SessionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionId.Unmarshal(m, b)
}
func (m *SessionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionId.Marshal(b, m, deterministic)
}
func (m *SessionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionId.Merge(m, src)
}
func (m *SessionId) XXX_Size() int {
	return xxx_messageInfo_SessionId.Size(m)
}
func (m *SessionId) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionId.DiscardUnknown(m)
}

var xxx_messageInfo_SessionId proto.InternalMessageInfo

func (m *SessionId) GetBinaryUuid() []byte {
	if m != nil {
		return m.BinaryUuid
	}
	return nil
}

type Session struct {
	SessionId            *SessionId `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PersonaId            *PersonaId `protobuf:"bytes,2,opt,name=persona_id,json=personaId,proto3" json:"persona_id,omitempty"`
	StartDatetimeMs      int64      `protobuf:"varint,3,opt,name=start_datetime_ms,json=startDatetimeMs,proto3" json:"start_datetime_ms,omitempty"`
	ExpireDatetimeMs     int64      `protobuf:"varint,4,opt,name=expire_datetime_ms,json=expireDatetimeMs,proto3" json:"expire_datetime_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e499f99b96a51ec, []int{16}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSessionId() *SessionId {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *Session) GetPersonaId() *PersonaId {
	if m != nil {
		return m.PersonaId
	}
	return nil
}

func (m *Session) GetStartDatetimeMs() int64 {
	if m != nil {
		return m.StartDatetimeMs
	}
	return 0
}

func (m *Session) GetExpireDatetimeMs() int64 {
	if m != nil {
		return m.ExpireDatetimeMs
	}
	return 0
}

func init() {
	proto.RegisterEnum("UserType", UserType_name, UserType_value)
	proto.RegisterEnum("UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("PersonaType", PersonaType_name, PersonaType_value)
	proto.RegisterEnum("PersonaStatus", PersonaStatus_name, PersonaStatus_value)
	proto.RegisterEnum("OrgType", OrgType_name, OrgType_value)
	proto.RegisterEnum("OrgStatus", OrgStatus_name, OrgStatus_value)
	proto.RegisterEnum("GroupType", GroupType_name, GroupType_value)
	proto.RegisterEnum("GroupVisibility", GroupVisibility_name, GroupVisibility_value)
	proto.RegisterEnum("GroupStatus", GroupStatus_name, GroupStatus_value)
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("MessageStatus", MessageStatus_name, MessageStatus_value)
	proto.RegisterType((*UserId)(nil), "UserId")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*PersonaId)(nil), "PersonaId")
	proto.RegisterType((*Persona)(nil), "Persona")
	proto.RegisterType((*OrgId)(nil), "OrgId")
	proto.RegisterType((*Org)(nil), "Org")
	proto.RegisterType((*GroupId)(nil), "GroupId")
	proto.RegisterType((*Group)(nil), "Group")
	proto.RegisterType((*MessageId)(nil), "MessageId")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageRef)(nil), "MessageRef")
	proto.RegisterType((*DocId)(nil), "DocId")
	proto.RegisterType((*Doc)(nil), "Doc")
	proto.RegisterType((*Auth)(nil), "Auth")
	proto.RegisterType((*Auth_PersonaRef)(nil), "Auth.PersonaRef")
	proto.RegisterType((*AuthRec)(nil), "AuthRec")
	proto.RegisterType((*SessionId)(nil), "SessionId")
	proto.RegisterType((*Session)(nil), "Session")
}

func init() { proto.RegisterFile("sliki-model.proto", fileDescriptor_5e499f99b96a51ec) }

var fileDescriptor_5e499f99b96a51ec = []byte{
	// 1277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x36, 0xf5, 0x87, 0x14, 0x47, 0xb2, 0x4d, 0x6f, 0xf2, 0xc3, 0x4f, 0x49, 0x9b, 0x46, 0x51,
	0x82, 0x40, 0x11, 0x1c, 0x25, 0x4d, 0x81, 0x22, 0xe8, 0x4d, 0x8e, 0x68, 0x85, 0x80, 0x2c, 0x19,
	0x4b, 0xc9, 0x57, 0x82, 0x36, 0x57, 0xf2, 0x22, 0x92, 0x48, 0x70, 0xa9, 0xc4, 0xea, 0x73, 0x14,
	0x7d, 0x97, 0xbe, 0x44, 0x8f, 0x3d, 0xf7, 0x15, 0x7a, 0xeb, 0xb1, 0xd8, 0xe5, 0x92, 0xa2, 0x65,
	0x39, 0x91, 0x2f, 0x69, 0x4f, 0x5a, 0xce, 0x7c, 0x33, 0xcb, 0xfd, 0xbe, 0xd9, 0xe1, 0x08, 0x0e,
	0xd8, 0x94, 0x7e, 0xa0, 0x2f, 0x67, 0xbe, 0x47, 0xa6, 0xad, 0x20, 0xf4, 0x23, 0xbf, 0xfe, 0x02,
	0xd4, 0x11, 0x23, 0xa1, 0xe5, 0xa1, 0xc7, 0x50, 0x3e, 0xa7, 0x73, 0x37, 0x5c, 0x3a, 0x8b, 0x05,
	0xf5, 0xaa, 0x4a, 0x4d, 0x69, 0x54, 0x30, 0xc4, 0xa6, 0xd1, 0x82, 0x7a, 0xf5, 0x5f, 0xf3, 0x50,
	0xe0, 0x58, 0x54, 0x03, 0x6d, 0xc1, 0x48, 0xe8, 0x48, 0x54, 0xf9, 0x8d, 0xd6, 0x8a, 0x73, 0x60,
	0x75, 0x11, 0xe7, 0x7a, 0x0e, 0xba, 0x40, 0x44, 0xcb, 0x80, 0x54, 0x73, 0x35, 0xa5, 0xb1, 0xf7,
	0x46, 0x17, 0x98, 0xe1, 0x32, 0x20, 0xb8, 0xb4, 0x90, 0x2b, 0xf4, 0x14, 0x54, 0x16, 0xb9, 0xd1,
	0x82, 0x55, 0xf3, 0x02, 0x54, 0x16, 0x20, 0x5b, 0x98, 0xb0, 0x74, 0xa1, 0x16, 0xdc, 0xbb, 0x08,
	0x89, 0x1b, 0x11, 0xcf, 0xf1, 0xdc, 0x88, 0x44, 0x74, 0x46, 0x9c, 0x19, 0xab, 0x16, 0x6a, 0x4a,
	0x23, 0x8f, 0x0f, 0xa4, 0xab, 0x23, 0x3d, 0x27, 0x0c, 0xbd, 0x86, 0xfb, 0x33, 0xdf, 0xa3, 0x63,
	0xba, 0x16, 0x50, 0x14, 0x01, 0x28, 0xf1, 0x65, 0x22, 0x1e, 0x01, 0x4c, 0xe8, 0x47, 0x32, 0x77,
	0xe6, 0xee, 0x8c, 0x54, 0xd5, 0x9a, 0xd2, 0xd0, 0xb1, 0x2e, 0x2c, 0x7d, 0x77, 0x46, 0x38, 0x33,
	0x63, 0x77, 0x46, 0xa7, 0xcb, 0xd8, 0xaf, 0x09, 0x3f, 0xc4, 0x26, 0x01, 0x78, 0x02, 0x15, 0x8f,
	0xb2, 0x60, 0xea, 0x4a, 0x44, 0x49, 0x20, 0xca, 0xd2, 0x26, 0x20, 0x35, 0x28, 0x7b, 0x84, 0x5d,
	0x84, 0x34, 0x88, 0xa8, 0x3f, 0xaf, 0xea, 0x12, 0xb1, 0x32, 0xa1, 0xb7, 0x80, 0x3c, 0x32, 0x76,
	0x17, 0xd3, 0xc8, 0x09, 0x48, 0xc8, 0xfc, 0xb9, 0xcb, 0x09, 0x06, 0x41, 0x30, 0xb4, 0x4e, 0x63,
	0x93, 0xe5, 0x61, 0x43, 0xa2, 0x52, 0x4b, 0xfd, 0x10, 0xf4, 0xf4, 0xe1, 0xcb, 0x32, 0xfe, 0x91,
	0x03, 0x4d, 0xc2, 0xd1, 0x0b, 0x80, 0xcc, 0x5e, 0xca, 0x8d, 0xbd, 0xf4, 0x20, 0xcd, 0xfb, 0x0a,
	0x2a, 0x09, 0x34, 0xa3, 0x6a, 0x25, 0x01, 0x0b, 0x61, 0xcb, 0xc1, 0xea, 0x01, 0x3d, 0x5f, 0xd3,
	0x76, 0x2f, 0x81, 0xae, 0xc9, 0x9b, 0xa9, 0xa6, 0xc2, 0xe6, 0x6a, 0xba, 0xa5, 0x00, 0x8a, 0x77,
	0x2d, 0x00, 0xf5, 0xd6, 0x02, 0x58, 0x17, 0x50, 0xfb, 0xa2, 0x80, 0xa5, 0x1b, 0x02, 0xd6, 0x1b,
	0x50, 0x1c, 0x84, 0x93, 0x6d, 0x24, 0xf8, 0x25, 0x07, 0xf9, 0x41, 0x38, 0x41, 0x8f, 0x40, 0xf5,
	0xc3, 0xc9, 0x8a, 0x7a, 0xb5, 0x25, 0x12, 0xe0, 0xa2, 0x2f, 0xf2, 0x3c, 0x85, 0x12, 0x77, 0x67,
	0xe8, 0x2e, 0x71, 0x80, 0xa0, 0x5a, 0xf3, 0xe3, 0x05, 0xaa, 0xaf, 0xd1, 0x0c, 0x1c, 0xf2, 0xd5,
	0x6f, 0xd0, 0x3a, 0x81, 0xea, 0x17, 0x09, 0xd4, 0x6e, 0x12, 0xd8, 0x04, 0xad, 0x1b, 0xfa, 0x8b,
	0x60, 0xcb, 0x2a, 0x2e, 0x0a, 0x30, 0x67, 0x69, 0xc2, 0x17, 0x2b, 0x1a, 0x4b, 0x2d, 0x99, 0x06,
	0x6b, 0x13, 0x99, 0xef, 0x05, 0x40, 0x0c, 0xca, 0x90, 0x09, 0x31, 0x4c, 0xd0, 0xa9, 0x4f, 0x92,
	0x25, 0x7a, 0x0d, 0xf0, 0x91, 0x32, 0x7a, 0x4e, 0xa7, 0x34, 0x5a, 0x4a, 0x52, 0x8d, 0x18, 0x7a,
	0x96, 0xda, 0x71, 0x06, 0x83, 0x9e, 0xa5, 0x12, 0x14, 0xe4, 0xa5, 0x10, 0xe8, 0xed, 0x44, 0xf8,
	0xaf, 0x55, 0xf1, 0x21, 0xe8, 0x27, 0x84, 0x31, 0x77, 0x42, 0xb6, 0x91, 0xe1, 0xef, 0x1c, 0x68,
	0x12, 0xce, 0x39, 0x9e, 0xc5, 0xcb, 0x6c, 0x33, 0x49, 0x93, 0x61, 0x7d, 0x96, 0xe6, 0x7d, 0x05,
	0x95, 0x04, 0x7a, 0xad, 0x99, 0x48, 0x70, 0xdc, 0x4c, 0x66, 0xab, 0x87, 0x0d, 0xcd, 0x44, 0x42,
	0xbf, 0x7a, 0xa5, 0xbf, 0x05, 0x94, 0xec, 0x90, 0x69, 0x9d, 0xea, 0xcd, 0x36, 0x2d, 0x51, 0xab,
	0xce, 0xdc, 0x84, 0xdd, 0xd8, 0xe6, 0xc8, 0x4b, 0xaf, 0x5d, 0xbb, 0xf4, 0xe5, 0xd8, 0x19, 0xb7,
	0x90, 0x27, 0x2b, 0x82, 0xce, 0x7d, 0x6f, 0x99, 0x08, 0x25, 0x6d, 0x47, 0xbe, 0xb7, 0xac, 0xff,
	0x0c, 0x20, 0x39, 0xc0, 0x64, 0x8c, 0x5e, 0xc3, 0x5e, 0x48, 0xc6, 0xce, 0x67, 0x05, 0xa8, 0x84,
	0x64, 0xbc, 0xd2, 0xf6, 0x27, 0xb8, 0xe7, 0x87, 0x74, 0x42, 0xe7, 0xee, 0x34, 0x1b, 0x96, 0xbb,
	0x11, 0x76, 0x90, 0xc0, 0x52, 0x13, 0x6f, 0x75, 0x1d, 0xff, 0x62, 0x9b, 0x02, 0x79, 0x06, 0xf9,
	0x8e, 0x7f, 0xc1, 0x3b, 0x9d, 0xe7, 0x5f, 0x64, 0x3b, 0x9d, 0x88, 0xc7, 0x45, 0x8f, 0xff, 0xd4,
	0xff, 0xca, 0x43, 0xa1, 0xbd, 0x88, 0x2e, 0xb7, 0x18, 0x2d, 0x0e, 0xa1, 0x24, 0x79, 0x67, 0xd5,
	0x5c, 0x2d, 0xdf, 0x28, 0xbf, 0x31, 0x5a, 0x3c, 0x34, 0xa1, 0x1e, 0x93, 0x31, 0x4e, 0x11, 0xb7,
	0xd5, 0x43, 0xfe, 0xae, 0xf5, 0x50, 0xb8, 0xb5, 0x1e, 0x9a, 0x70, 0x30, 0xf5, 0x27, 0x74, 0xbe,
	0xe1, 0x8e, 0xee, 0x0b, 0x47, 0x06, 0xdb, 0x00, 0x23, 0xc6, 0xd2, 0xc0, 0x71, 0x3d, 0x2f, 0x24,
	0x8c, 0x89, 0x22, 0xa8, 0xe0, 0x3d, 0x61, 0xb7, 0x82, 0x76, 0x6c, 0x7d, 0xf8, 0xa7, 0x02, 0xb0,
	0x3a, 0x10, 0x7a, 0x00, 0x25, 0x72, 0x15, 0xc5, 0xb7, 0x5a, 0x11, 0xa5, 0xa0, 0x91, 0xab, 0x48,
	0xdc, 0xe8, 0xeb, 0x9f, 0xf0, 0xdc, 0xe7, 0x3e, 0xe1, 0xff, 0x12, 0x19, 0xc5, 0x8d, 0x64, 0xd4,
	0x67, 0xa0, 0x71, 0xdd, 0x30, 0xb9, 0x40, 0xff, 0x03, 0x95, 0x1f, 0x4f, 0x8a, 0xae, 0xe3, 0x22,
	0xb9, 0x8a, 0x2c, 0x0f, 0xfd, 0x1f, 0xb4, 0xe0, 0x93, 0x73, 0xe9, 0xb2, 0x4b, 0x71, 0xae, 0x0a,
	0x56, 0x83, 0x4f, 0xef, 0x5d, 0x76, 0x29, 0x1d, 0xcc, 0x9d, 0x46, 0xe2, 0xe5, 0x85, 0xc3, 0x76,
	0xa7, 0x11, 0x7a, 0x00, 0x05, 0x77, 0x11, 0x5d, 0xca, 0x41, 0xa2, 0x28, 0x0a, 0x03, 0x0b, 0x13,
	0xef, 0x6b, 0x36, 0x61, 0x8c, 0xfa, 0xf3, 0x6d, 0xca, 0xf6, 0x37, 0x05, 0x34, 0x09, 0xe7, 0x0c,
	0xb3, 0x78, 0x99, 0xbd, 0x56, 0x69, 0x32, 0xac, 0xb3, 0x34, 0xef, 0x1d, 0xc4, 0x68, 0xc2, 0x01,
	0x8b, 0xdc, 0x30, 0xda, 0x20, 0xc5, 0xbe, 0x70, 0x64, 0x68, 0x3d, 0x04, 0x44, 0xae, 0x02, 0x1a,
	0x92, 0x0d, 0x32, 0x18, 0xb1, 0x67, 0x85, 0x6e, 0x7e, 0x0f, 0xa5, 0x64, 0xd4, 0x46, 0x07, 0xb0,
	0x3b, 0xb2, 0x4d, 0xec, 0x9c, 0x9a, 0xd8, 0x1e, 0xf4, 0xdb, 0x3d, 0x63, 0x07, 0x21, 0xd8, 0x13,
	0xa6, 0x01, 0xee, 0x3a, 0x47, 0x6d, 0xdb, 0xec, 0x18, 0x4a, 0xf3, 0x18, 0x60, 0x35, 0x78, 0xa3,
	0x7d, 0x28, 0x0b, 0x44, 0xfb, 0xdd, 0xd0, 0x3a, 0x33, 0x8d, 0x1d, 0x74, 0x0f, 0xf6, 0x85, 0x61,
	0xd4, 0x3f, 0x33, 0xb1, 0x75, 0x6c, 0xf1, 0x98, 0x34, 0x8f, 0x3d, 0xb2, 0x4f, 0xcd, 0x7e, 0xc7,
	0xec, 0x18, 0xb9, 0x66, 0x1d, 0xca, 0x99, 0x79, 0x90, 0xc7, 0xc9, 0x8d, 0x1d, 0x6c, 0x76, 0x47,
	0xbd, 0x36, 0x36, 0x76, 0x9a, 0x4f, 0x61, 0xf7, 0xda, 0x20, 0xc8, 0x13, 0x25, 0xa8, 0x64, 0xc7,
	0xe6, 0xef, 0x0a, 0x68, 0x72, 0xd4, 0x41, 0x55, 0xb8, 0xcf, 0xdf, 0xb5, 0x3f, 0xe8, 0x3b, 0xa7,
	0x78, 0x70, 0x6c, 0x0d, 0x9d, 0xc1, 0xf0, 0xbd, 0x89, 0x8d, 0x1d, 0xf4, 0x1d, 0x3c, 0x5c, 0xf3,
	0x98, 0x9d, 0xd1, 0xbb, 0xf6, 0xd0, 0x12, 0x47, 0x55, 0xd0, 0xb7, 0x50, 0x5d, 0xf3, 0x63, 0xb3,
	0x67, 0x75, 0xad, 0xc1, 0xc8, 0x36, 0x72, 0xe8, 0x11, 0x3c, 0x58, 0xf3, 0x76, 0x07, 0x67, 0x26,
	0xee, 0x9f, 0x98, 0xfd, 0xa1, 0x91, 0x4f, 0xb6, 0x3d, 0x1e, 0xe0, 0xeb, 0xdb, 0x16, 0x36, 0x78,
	0xec, 0x93, 0x76, 0xaf, 0x67, 0x14, 0x37, 0x78, 0x7a, 0x6d, 0xdc, 0x35, 0x0d, 0xb5, 0xf9, 0x0d,
	0xe8, 0xe9, 0x5c, 0x86, 0xf6, 0x00, 0x38, 0x2c, 0x3d, 0x6d, 0x0b, 0xf4, 0x74, 0x14, 0xe1, 0x74,
	0x74, 0xf1, 0x60, 0x74, 0x9a, 0xd5, 0x6c, 0x17, 0xf4, 0xd8, 0x36, 0xc0, 0x5d, 0x43, 0x69, 0xfe,
	0x08, 0xfb, 0x6b, 0xf3, 0x08, 0x32, 0xa0, 0x22, 0xa3, 0x46, 0x47, 0x3d, 0xeb, 0x9d, 0xb1, 0xc3,
	0xa5, 0x97, 0x16, 0x6c, 0x9d, 0xb5, 0x87, 0xa6, 0xa1, 0x34, 0x1f, 0x43, 0x39, 0x33, 0x99, 0xac,
	0x62, 0xd2, 0x17, 0x79, 0x09, 0xe5, 0xcc, 0x27, 0x98, 0xbf, 0xe7, 0x89, 0xdd, 0x75, 0x6c, 0xeb,
	0xe4, 0xb4, 0xc7, 0xeb, 0x40, 0x3e, 0x0f, 0xdf, 0x63, 0xb3, 0xcd, 0xcb, 0xa6, 0x06, 0xbb, 0xd7,
	0x3e, 0xc3, 0xbc, 0x72, 0x38, 0xe0, 0xcc, 0xb2, 0xad, 0x23, 0x1e, 0x71, 0x84, 0xc0, 0xf8, 0x44,
	0x3f, 0xd0, 0x96, 0xf8, 0xe3, 0xd9, 0x12, 0x7f, 0x3c, 0xcf, 0x55, 0xf1, 0xcf, 0xf3, 0x87, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x12, 0xd1, 0x94, 0x8e, 0x0e, 0x00, 0x00,
}
